CREATE TABLE images (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  path VARCHAR(100),
  size VARCHAR(100) NOT NULL UNIQUE,
  originalName VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  fullName BOOLEAN NOT NULL DEFAULT 0,
  meta TEXT CHARACTER SET binary
);
